name: Docker
on:
  push:
    branches: [ main ]
    paths:
      - 'trigger.txt'
env:
  REGISTRY_REGION: shanghai
  REGISTRY: registry.cn-${{ env.REGISTRY_REGION }}.aliyuncs.com
jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          trigger.txt
        sparse-checkout-cone-mode: false
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ALIYUN_REGISTRY_USER }}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
    - name: Docker pull image
      run: |
        docker pull $(cat trigger.txt)
    - name: Docker push image
      run: |
        docker push ${{ env.REGISTRY }}/$(cat trigger.txt)
